
spring:
  application:
    name: table-finder
  datasource:
    url: jdbc:postgresql://localhost:5432/tablefinderdb
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration